---
- name: EC2 Provision Scripts
  hosts: localhost
  connection: local
  gather_facts: true
  vars_prompt:
    - name: "vpc_id"
      prompt: "VPC id?"
      private: no
    - name: "ec2_keypair"
      prompt: "Keypair?"
      private: no
      confirm: yes
      default: ""    
  vars:
    ec2_region: "eu-west-2"
    zone: "a"
    availability_zone: "{{ec2_region}}{{zone}}"
    ec2_image: "ami-00a1896be20551dc8"
    storage_size: 100
    ec2_instance_type: "t2.medium"
    ec2_Name: test
    ec2_role: test
  pre_tasks:
    - assert:
        that:
          - "vpc_id is defined"
    - ec2_vpc_net_info:
        vpc_ids: "{{vpc_id}}"
      register: vpc
    - set_fact:
        host_env: "{{ (vpc|json_query(query)) if (vpc|json_query(query)) is defined and (vpc|json_query(query))!='' else '' }}"
      vars:
        query: 'vpcs[0].tags.Name'
    - debug: var=host_env
    - ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{vpc_id}}"
      register: subnet_info
    - set_fact:
        subnet_id: "{{ subnet_info| json_query(query)|first}}"
      vars:
        query: "subnets[?availability_zone == '{{availability_zone}}'].id"
    - debug: var=subnet_id
  roles:
    - Provision
