{
 "title": "Polkadot node metrics",
 "description": "Grafana dashboard for Polkadot node metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "polkadot_memory_usage_bytes", "legendFormat": "{{instance}}-{{job}}" }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "polkadot_cpu_usage_percentage", "legendFormat": "{{instance}}-{{job}}" }
   ]
  },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "polkadot_block_height_number",
     "legendFormat": "{{status}} ({{instance}}-{{job}})"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 8 },
   "targets": [
    { "expr": "polkadot_network_per_sec_bytes", "legendFormat": "{{direction}} ({{instance}})" }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "polkadot_ready_transactions_number",
     "legendFormat": "Number of transactions in the ready queue ({{instance}}-{{job}})"
    }
   ]
  },
  {
   "title": "Number of network gossip peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "polkadot_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers ({{instance}}-{{job}})"
    }
   ]
  }
 ]
}