 # A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  - job_name: 'alice_polka_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.28.1.1:9615']
        labels:
          instance: 'alice'
  - job_name: 'bob_polka_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.28.1.2:9616']
        labels:
          instance: 'bob'