version: '3'
services:
  node_alice:
    image: parity/polkadot
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "9615:9615"
    command: --chain=dev --alice --prometheus-external
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  node_bob:
    image: parity/polkadot
    ports:
      - "30344:30344"
      - "9935:9935"
      - "9945:9945"
      - "9616:9616"
    links:
      - "node_alice:alice"
    command: --chain=dev --bob --prometheus-external --prometheus-port 9616 --port 30344 --rpc-port 9935 --ws-port 9945 --bootnodes '/ip4/172.28.1.1/tcp/30333/p2p/QmT3voeSQKAJvzjUKJQ3QZcHe1bSrbJ8YscBbN13Cy6no2'
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
  prometheus:
    image: prom/prometheus
    volumes:
      - "/tmp/files/monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16